language: cpp
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "VKCmVzcnJe58/2F5ciPa6FQqnNi/MAUott/rMEFEim9Qk9cFeEuhhhb8JvjoKT1NVC2j+3VJgSczwHtoi06jKUHFqMWJ9pQEa7sNuStSfUGF7ADEjmvooXE/c0nKw5IZf2+pVk3HjvsJerUPOgcSEZSB8JvA7Lb3K1TPEW82xgm7okonE60kz1m0/oDQAAAbocY0uswOPhu5wZ2Df7nseSrLpI56SepHF2r8SJRleeWfMO31inEhexOOqzS5dAE/tTjLjH+nI03JzJA2S3ugkVvU/zs9Ib2xgqWO5JTvk2waOKBnNAaOg9V6S6gYfNt5It0bzeFifzauP6Z7zBuaOJaRKQ+x+dehIv09wgLben2kacJOTI9fjZ7IflYHZH4+rs6eIGcem+C6T64OW0fjkbGnOjSH0wa4uhOacVigNWZik85Ro1JMk6wSDHBmmzjJZ8zmMbBSwd5Za/t8YfffP9y6/250R772tCOeI9Su3Fg+SuWzP3XoaHKbVrKZrrC5mlKnnACgV59E9fQUFJOfVXixGJ09d3hfA48BKoKKXEm9vY4JVSw5gSczJAdLHPGyY37s5nMXuJUY8fVf1bhNJ4iDwWVcQJDF1lJXMFV01pNsSb9xGnyKm+wfOI/HyCQfX3kHHfExrZ2I2he84vV4Sll4Rx1eWluWAbXSSLca4NU="

addons:
  coverity_scan:
    project:
      name: "kvirc/coverity"
      description: "Build submitted via Travis CI"
    notification_email: alexey+kvirccoverity@asokolov.org
    build_command_prepend: "mkdir build; cd build; cmake ..; cd .."
    build_command: "make -C build -j 3"
    branch_pattern: coverity_scan

script:
  - /bin/true
sudo: required
dist: trusty
